# Unify Elements vs NextSeq sample naming

In [ ]:


elements_esv = pd.read_parquet("/data/luka.lenaroto/eDentity/ITS-comparison/elements/elements_apscale/8_esv_table/elements_ESV_table.parquet.snappy")
elements_esv.head()
elements_esv.to_csv("/data/luka.lenaroto/eDentity/ITS-comparison/elements/elements_apscale/8_esv_table/elements_ESV_table.tsv.gz", index=False, sep="\t", compression="gzip")

In [ ]:
elements_esv.columns[:5]

Index(['temporary_ID', 'unique_ID',
       '4854_1084_ITSmix-SB_92_S1088_L001_reformated',
       '4854_1302_ITS-SB_118_S1306_L001_reformated',
       '4854_0605_ITSmix-NL2_29_S609_L001_reformated'],
      dtype='object')

In [ ]:
elements_colmuns = []
elements_markers = []
for col in elements_esv.columns:
    if "ITS" in col:
        if "Blank" in col:            
            #new_name = f'{col.split("_")[3]}_{col.split("_")[2]}'
            elements_colmuns.append(f'{col.split("_")[3]}')
            elements_markers.append(f'{col.split("_")[2]}')
        else:
            #new_name = f'{col.split("_")[4]}_{col.split("_")[2]}'
            elements_colmuns.append(f'{col.split("_")[4]}')
            elements_markers.append(f'{col.split("_")[2]}')
    else:
        elements_colmuns.append(col)
print(elements_colmuns[:10])

['temporary_ID', 'unique_ID', 'S1088', 'S1306', 'S609', 'S1284', 'S183', 'S1114', 'S1117', 'S226']

In [ ]:
elements_esv.columns = elements_colmuns
elements_esv.head()

,temporary_ID,unique_ID,S1088,S1306,S609,S1284,S183,S1114,S1117,S226,...,S201,S221,S1150,S678,S1106,S1087,S262,S667,S1067,Seq
0,ESV_1,701c91a6a42996d15edbdbb0c2f8c9a83f4a95d81e7804...,0.0,0.0,0.0,86053.0,0.0,0.0,0.0,1381.0,...,0.0,171.0,0,0.0,0.0,0.0,7061.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTT...
1,ESV_2,5856f106b1a2cdf6889dcfaac4be8b3663417cae81c84d...,0.0,4.0,0.0,175.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTC...
2,ESV_3,fdd5f6049c61571e09a640ca055cfb98876cc147dcff54...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117.0,...,60512.0,8.0,0,3261.0,0.0,0.0,4.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAATCATCGAGTC...
3,ESV_4,266c738ec05e0e47ec3bfc3487e92735e18d9614d7a3de...,0.0,0.0,0.0,30911.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTT...
4,ESV_5,34faa8c95c3c62e204b7d83a0c932118fa6794350fe9ab...,37.0,0.0,0.0,0.0,0.0,10.0,13.0,0.0,...,0.0,0.0,0,0.0,291.0,0.0,0.0,0.0,0.0,CGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCG...

In [ ]:
nextseq_esv = pd.read_parquet("/data/luka.lenaroto/eDentity/ITS-comparison/NextSeq/NextSeq_apscale/8_esv_table/NextSeq_ESV_table.parquet.snappy")
nextseq_esv.to_csv("/data/luka.lenaroto/eDentity/ITS-comparison/NextSeq/NextSeq_apscale/8_esv_table/NextSeq_ESV_table.tsv.gz", index=False, sep="\t", compression="gzip")
nextseq_esv.head()

,temporary_ID,unique_ID,ITSmix-SB_21_S661,ITS-NL2_15_S682,ITS-SB_31_S767,ITSmix-SB_126_S1118,ITS-NL2_16_S681,ITSmix-SB_141_S1133,ITSmix-NL2_117_S113,ITSmix-SB_140_S1132,...,ITS-NL2_102_S194,ITSmix-NL2_14_S590,ITS-NL2_4_S676,ITS-SB_119_S1303,ITSmix-SB_118_S1110,ITSmix-SB_84_S1076,ITSmix-NL2_50_S626,ITS-NL2_30_S702,ITSmix-NL2_43_S619,Seq
0,ESV_1,701c91a6a42996d15edbdbb0c2f8c9a83f4a95d81e7804...,15.0,26.0,1500.0,0.0,0.0,0.0,0.0,0.0,...,0.0,122.0,67.0,18124.0,0.0,0.0,26.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTT...
1,ESV_2,34faa8c95c3c62e204b7d83a0c932118fa6794350fe9ab...,0.0,0.0,0.0,0.0,0.0,135.0,0.0,117.0,...,0.0,0.0,0.0,0.0,187.0,48.0,0.0,137.0,0.0,CGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCG...
2,ESV_3,5856f106b1a2cdf6889dcfaac4be8b3663417cae81c84d...,0.0,0.0,0.0,0.0,0.0,0.0,139.0,0.0,...,0.0,0.0,0.0,202.0,0.0,0.0,0.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTC...
3,ESV_4,fdd5f6049c61571e09a640ca055cfb98876cc147dcff54...,38.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,81626.0,0.0,140.0,0.0,0.0,47.0,37.0,0.0,95.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAATCATCGAGTC...
4,ESV_5,bda8cb3a08f6e2f6990addfa996871ac2106c9fc3b5888...,0.0,0.0,0.0,25436.0,62.0,111.0,96.0,146.0,...,111.0,0.0,0.0,0.0,151.0,70.0,0.0,213.0,46.0,CGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCG...

In [ ]:
nextseq_columns= []
nextseq_markers = []
for col in nextseq_esv.columns:
    
    if "ITS" in col:
        if "Blank" in col:
            # new_name = f'{col.split("_")[1]}_{col.split("_")[0]}'
            nextseq_columns.append(f'{col.split("_")[1]}')
            nextseq_markers.append(f'{col.split("_")[0]}')
        else:
            #new_name = f'{col.split("_")[2]}_{col.split("_")[0]}'
            nextseq_columns.append(f'{col.split("_")[2]}')
            nextseq_markers.append(f'{col.split("_")[0]}')
    else:
        nextseq_columns.append(col)
print(nextseq_columns[:10], nextseq_markers[:10])

['temporary_ID', 'unique_ID', 'S661', 'S682', 'S767', 'S1118', 'S681', 'S1133', 'S113', 'S1132'] ['ITSmix-SB', 'ITS-NL2', 'ITS-SB', 'ITSmix-SB', 'ITS-NL2', 'ITSmix-SB', 'ITSmix-NL2', 'ITSmix-SB', 'ITS-NL2', 'ITSmix-SB']

In [ ]:
nextseq_esv.columns = nextseq_columns
nextseq_esv.head()

,temporary_ID,unique_ID,S661,S682,S767,S1118,S681,S1133,S113,S1132,...,S194,S590,S676,S1303,S1110,S1076,S626,S702,S619,Seq
0,ESV_1,701c91a6a42996d15edbdbb0c2f8c9a83f4a95d81e7804...,15.0,26.0,1500.0,0.0,0.0,0.0,0.0,0.0,...,0.0,122.0,67.0,18124.0,0.0,0.0,26.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTT...
1,ESV_2,34faa8c95c3c62e204b7d83a0c932118fa6794350fe9ab...,0.0,0.0,0.0,0.0,0.0,135.0,0.0,117.0,...,0.0,0.0,0.0,0.0,187.0,48.0,0.0,137.0,0.0,CGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCG...
2,ESV_3,5856f106b1a2cdf6889dcfaac4be8b3663417cae81c84d...,0.0,0.0,0.0,0.0,0.0,0.0,139.0,0.0,...,0.0,0.0,0.0,202.0,0.0,0.0,0.0,0.0,0.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCGAGTC...
3,ESV_4,fdd5f6049c61571e09a640ca055cfb98876cc147dcff54...,38.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,81626.0,0.0,140.0,0.0,0.0,47.0,37.0,0.0,95.0,ATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAATCATCGAGTC...
4,ESV_5,bda8cb3a08f6e2f6990addfa996871ac2106c9fc3b5888...,0.0,0.0,0.0,25436.0,62.0,111.0,96.0,146.0,...,111.0,0.0,0.0,0.0,151.0,70.0,0.0,213.0,46.0,CGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGCGAATCATCG...

In [ ]:
nextseq_esv.shape, elements_esv.shape

((34535, 486), (15354, 486))

In [ ]:
intersection = set(elements_esv.columns).intersection(set(nextseq_esv.columns))
non_intersect = set(elements_esv.columns).difference(set(nextseq_esv.columns))

In [ ]:
non_intersect

{'S103',
 'S105',
 'S106',
 'S1071',
 'S111',
 'S112',
 'S1128',
 'S1140',
 'S1141',
 'S1149',
 'S1154',
 'S1155',
 'S1156',
 'S120',
 'S1257',
 'S126',
 'S1260',
 'S1268',
 'S1269',
 'S127',
 'S1279',
 'S1282',
 'S1293',
 'S1294',
 'S1295',
 'S1308',
 'S1319',
 'S1320',
 'S1329',
 'S1331',
 'S1341',
 'S1343',
 'S1346',
 'S1348',
 'S141',
 'S143',
 'S150',
 'S152',
 'S153',
 'S155',
 'S161',
 'S164',
 'S166',
 'S167',
 'S172',
 'S174',
 'S177',
 'S182',
 'S190',
 'S191',
 'S193',
 'S199',
 'S207',
 'S208',
 'S220',
 'S221',
 'S226',
 'S231',
 'S233',
 'S243',
 'S246',
 'S248',
 'S266',
 'S267',
 'S278',
 'S289',
 'S290',
 'S291',
 'S292',
 'S584',
 'S592',
 'S603',
 'S632',
 'S638',
 'S643',
 'S644',
 'S650',
 'S651',
 'S653',
 'S656',
 'S680',
 'S690',
 'S734',
 'S746',
 'S747',
 'S752',
 'S766',
 'S769',
 'S771',
 'S772'}

In [ ]:
len(intersection), len(non_intersect)

(396, 90)